In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

df = pd.read_csv("../data/t20_scores.csv")

X = df[["venue", "runs_10", "wickets_10"]]
y = df["final_score"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
X_train.head()

          venue  runs_10  wickets_10
232     Karachi       63           2
59   Rawalpindi       96           1
6       Karachi       71           1
185      Lahore       68           3
173  Rawalpindi       81           4

In [ ]:
num_cols = ["runs_10", "wickets_10"]
cat_cols = ["venue"]

preprocessor = ColumnTransformer([
    ("num", StandardScaler(), num_cols),
    ("cat", OneHotEncoder(handle_unknown="ignore", sparse_output=False), cat_cols),
])

          venue  runs_10  wickets_10  final_score
0       Karachi       75           3          144
1        Multan      101           4          160
2    Rawalpindi       55           4           85
3        Lahore      105           0          220
4        Lahore       85           4          135
..          ...      ...         ...          ...
295  Rawalpindi       99           3          193
296      Multan       87           3          155
297      Lahore       98           0          183
298      Lahore       90           0          170
299     Karachi       90           3          169

[300 rows x 4 columns]

In [5]:
preprocessor.fit(X_train)

X_train_ready = preprocessor.transform(X_train)
X_test_ready = preprocessor.transform(X_test)

print(X_train_ready.shape)
print(X_test_ready.shape)

(240, 6)
(60, 6)

In [6]:
print(preprocessor.get_feature_names_out())

['num__runs_10' 'num__wickets_10' 'cat__venue_Karachi' 'cat__venue_Lahore'
 'cat__venue_Multan' 'cat__venue_Rawalpindi']

In [7]:
pd.DataFrame(
    X_train_ready,
    columns=preprocessor.get_feature_names_out(),
    index=X_train.index,
).head()

,num__runs_10,num__wickets_10,cat__venue_Karachi,cat__venue_Lahore,cat__venue_Multan,cat__venue_Rawalpindi
232,-1.120492,-0.304610,1.0,0.0,0.0,0.0
59,0.798690,-0.875754,0.0,0.0,0.0,1.0
6,-0.655236,-0.875754,1.0,0.0,0.0,0.0
185,-0.829707,0.266534,0.0,1.0,0.0,0.0
173,-0.073666,0.837677,0.0,0.0,0.0,1.0

In [8]:
scaler_inside = preprocessor.named_transformers_["num"]
print("Mean:", scaler_inside.mean_)
print("Std: ", scaler_inside.scale_)

Mean: [82.26666667  2.53333333]
Std:  [17.19483126  1.7508728 ]